apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "ska"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "ska"
    spec:
      containers:
        - name: "ska"
          image: "acrbiker.azurecr.io/ska"
          ports:
          - containerPort: 80